name: Mi workflow

on: push

jobs:
  publish:
    runs-on: windows-2022
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.302'

      - name: Publicar proyecto
        shell: cmd
        run: '"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" "C:\Users\OracleFin11\source\repos\Template_Tesoreria\Template_Tesoreria.csproj" /p:Configuration=Release /p:PlatformTarget=x86 /p:PublishDir="C:\Users\OracleFin11\Documents\PUBLICACIONES\Template_Tesoreria"'

      - name: Generar número de versión
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $env:GITHUB_ENV

      - name: Registrar versión en SQL Server
        run: sqlcmd -S 10.128.10.19 -d dbTesoreria -U sa -P "SiFiAd1019" -Q "INSERT INTO [dbo].[Tbl_Tesoreria_VersionApp] (UrlDescarga, Version) VALUES ('\\\\10.115.0.14\\Finanzas\\Tesoreria\\Tesoreria-Template', '1.0.${{ github.run_number }}')"
