name: Mi workflow

on: push

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publicar proyecto
        run: dotnet publish ./Template_Tesoreria.csproj -c Release -o ./Documents/PUBLICACIONES/Template_Tesoreria /p:SignManifests=false

      - name: Generar número de versión
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $env:GITHUB_ENV

      - name: Registrar versión en SQL Server
        run: sqlcmd -S 10.128.10.19 -d dbTesoreria -U sa -P "SiFiAd1019" -Q "INSERT INTO [dbo].[Tbl_Tesoreria_VersionApp] (UrlDescarga, Version) VALUES ('\\\\10.115.0.14\\Finanzas\\Tesoreria\\Tesoreria-Template', '1.0.${{ github.run_number }}')"
