name: Mi workflow

on: push

jobs:
  publish:
    runs-on: windows-2022
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.302'

      - name: Compilar con MSBuild
        run: >
          & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
          "Template_Tesoreria.csproj"
          /p:Configuration=Release
          /p:PlatformTarget=x86
          /p:PublishDir="./publicaciones"
          /p:SignManifests=false